### ISSUE TITLE
godeltaprof: Support Go 1.22

### ISSUE THREAD

**Issue by stefanb** [grafana/pyroscope-go#86]
godeltaprof build tags in `internal/` specify Go behaviour only up to 1.21, not including the upcoming Go 1.22:
https://github.com/grafana/pyroscope-go/tree/main/godeltaprof/internal/pprof

Please add support also for Go 1.22

Eg, a test build with Go 1.22
* https://github.com/Homebrew/homebrew-core/pull/157782

reported:
```
  # github.com/pyroscope-io/godeltaprof/internal/pprof
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
``` 
In this case the reference to the new go module location is being updated in
* https://github.com/quay/clair/pull/1942

but this will not solve the Go 1.22 support until it is added here.

**Comment by stefanb** [comment]
Ah, i found 
* https://github.com/grafana/pyroscope-go/pull/55
So this should be already taken care of?
