### ISSUE TITLE
Failing to build in Go 1.23.0

### ISSUE THREAD

**Issue by replay** [grafana/pyroscope-go#117]
The build in Go 1.23.0 fails with the error:

```
#13 6.409 vendor/github.com/grafana/pyroscope-go/godeltaprof/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
#13 6.409 vendor/github.com/grafana/pyroscope-go/godeltaprof/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
```

**Comment by replay** [comment]
I updated the library from `0.1.6` to `0.1.7`, this solved the issue.
